## Week 1 
本周任務：
* 安裝 Anaconda 環境
* 註冊 github 帳號
* 初步探索 91APP 資料集

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os.path
%matplotlib inline

In [2]:
path = os.path.abspath(os.path.join(os.getcwd(), os.pardir)) + '/91APPdataset/' 
data = pd.read_csv(path+'Orders.csv')

/home/kevin/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head(3)

,DateId,MemberId,OrderGroupCode,TrackSourceTypeDef,TrackDeviceTypeDef,PayProfileTypeDef,SalesOrderSlaveId,SalePageId,IsMajor,IsGift,...,SalesOrderReceiverId,City,District,ZipCode,StoreName,StoreId,DeliverTypeDef,StatusDef,ReturnGoodsDateId,CauseDef
0,20150703,1388133,b'\xd0_\x8eby\xe8\x88\xa5\x85\xe4\x15\nMC\xeaO...,Web,Mobile,SevenEleven,4457777,1242871,True,False,...,1480890,嘉義縣,水上鄉,608.0,中庄門市,910828,SevenEleven,Finish,NaN,NaN
1,20150703,1388133,b'\xd0_\x8eby\xe8\x88\xa5\x85\xe4\x15\nMC\xeaO...,Web,Mobile,SevenEleven,4457778,1242880,True,False,...,1480890,嘉義縣,水上鄉,608.0,中庄門市,910828,SevenEleven,Finish,NaN,NaN
2,20150703,1388133,b'\xd0_\x8eby\xe8\x88\xa5\x85\xe4\x15\nMC\xeaO...,Web,Mobile,SevenEleven,4457779,1242880,True,False,...,1480890,嘉義縣,水上鄉,608.0,中庄門市,910828,SevenEleven,Finish,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5495276 entries, 0 to 5495275
Data columns (total 28 columns):
DateId                         int64
MemberId                       int64
OrderGroupCode                 object
TrackSourceTypeDef             object
TrackDeviceTypeDef             object
PayProfileTypeDef              object
SalesOrderSlaveId              int64
SalePageId                     int64
IsMajor                        bool
IsGift                         bool
IsSalePageGift                 bool
Quantity                       int64
UnitPrice                      float64
PromotionDiscount              float64
ECouponId                      int64
ECouponDiscount                float64
SalesOrderSlaveTotalPayment    float64
SalesOrderSlaveDateTime        object
SalesOrderReceiverId           int64
City                           object
District                       object
ZipCode                        float64
StoreName                      object
StoreId                        object
DeliverTypeDef                 object
StatusDef                      object
ReturnGoodsDateId              float64
CauseDef                       object
dtypes: bool(3), float64(6), int64(7), object(12)
memory usage: 1.0+ GB

In [5]:
data.describe()

,DateId,MemberId,SalesOrderSlaveId,SalePageId,Quantity,UnitPrice,PromotionDiscount,ECouponId,ECouponDiscount,SalesOrderSlaveTotalPayment,SalesOrderReceiverId,ZipCode,ReturnGoodsDateId
count,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495276e+06,5.495267e+06,2.832450e+05
mean,2.016521e+07,2.165717e+06,2.798377e+07,2.545703e+06,1.020664e+00,2.630405e+02,-2.513213e+01,7.692428e+03,-7.047799e+00,2.355160e+02,9.552483e+06,3.135510e+02,2.016600e+07
std,7.738558e+03,1.467033e+06,1.505576e+07,7.472451e+05,1.854327e-01,1.247388e+02,4.449524e+01,1.544671e+04,1.482828e+01,1.253341e+02,5.233755e+06,2.752423e+02,7.774344e+03
min,2.015051e+07,1.326000e+03,3.573759e+06,1.077959e+06,1.000000e+00,0.000000e+00,-3.005000e+03,0.000000e+00,-2.070000e+02,0.000000e+00,1.198563e+06,0.000000e+00,2.015052e+07
25%,2.016060e+07,1.018657e+06,1.490123e+07,1.974644e+06,1.000000e+00,1.990000e+02,-3.100000e+01,0.000000e+00,-8.000000e+00,1.670000e+02,4.971512e+06,1.030000e+02,2.016070e+07
50%,2.016121e+07,1.841363e+06,2.565071e+07,2.514525e+06,1.000000e+00,2.370000e+02,0.000000e+00,0.000000e+00,0.000000e+00,1.990000e+02,8.674492e+06,2.480000e+02,2.017011e+07
75%,2.017073e+07,3.138278e+06,4.016520e+07,3.097385e+06,1.000000e+00,3.200000e+02,0.000000e+00,9.907000e+03,0.000000e+00,2.980000e+02,1.379972e+07,4.280000e+02,2.017082e+07
max,2.018042e+07,6.771506e+06,5.797034e+07,4.268705e+06,1.000000e+01,3.500000e+03,0.000000e+00,7.309600e+04,0.000000e+00,1.432100e+04,2.000324e+07,9.830000e+02,2.018051e+07